name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
          - os: macos-latest-xlarge
            arch: arm64
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - name: Run builder
        run: |
          docker buildx build \
          --file tools/builder.Dockerfile \
          --load \
          --tag builder \
          --platform linux/${{ matrix.arch }} \
          --progress=plain \
          --no-cache \
          .
          docker run --rm -it --platform linux/${{ matrix.arch }} builder
          CONTAINER_ID=$(docker create -it --platform linux/${{ matrix.arch }} builder)
          docker cp $CONTAINER_ID:/boringssl/build/crypto/libcrypto.a ./libcrypto.a
          docker cp $CONTAINER_ID:/boringssl/build/ssl/libssl.a ./libssl.a
          tar -cJf boringssl-fips.tar.xz libcrypto.a libssl.a

      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          path: boringssl-fips.tar.xz
          name: boringssl-fips-${{ matrix.arch }}
