name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - run: |
          docker buildx build \
          --file tools/builder.Dockerfile \
          --load \
          --tag builder \
          --platform linux/arm64 \
          --no-cache \
          .
