name: release

on:
  push:
    tags:
      - "fips-*" # see: https://github.com/envoyproxy/envoy/blob/73dc561f0c227c03ec6535eaf4c30d16766236a0/bazel/repository_locations.bzl#L140C20-L140C33.

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - arm64
          - amd64
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
      - uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0
      - uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0
      - name: Run builder
        run: |
          docker buildx build \
            --file tools/builder.Dockerfile \
            --load \
            --tag builder \
            --platform linux/${{ matrix.arch }} \
            --no-cache \
            .
            CONTAINER_ID=$(docker create -it builder)
            docker cp $CONTAINER_ID:/boringssl/build/crypto/libcrypto.a ./libcrypto.a
            docker cp $CONTAINER_ID:/boringssl/build/ssl/libssl.a ./libssl.a
            tar cJf boringssl-fips.tar.xz libcrypto.a libssl.a

      - uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3.1.3
        with:
          path: boringssl-fips.tar.xz
          name: boringssl-fips-${{ matrix.arch }}

  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    needs: build
    steps:
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3.0.2
      - run: |
          gh release create ${{ github.ref_name }} \
            boringssl-fips-amd64/boringssl-fips.tar.xz boringssl-fips-arm64/boringssl-fips.tar.xz \
            -n ${{ github.ref_name }} \
            -t ${{ github.ref_name }}
        env:
          GH_TOKEN: ${{ github.token }}
